### ISSUE TITLE
Rewrite in typescript

### ISSUE THREAD

**Issue by lokshunhung** [jest-community/create-jest-runner#39]
☑️ I am willing to work on this issue.

This is a proposal to rewrite the whole project in typescript.  
The compilation will continue to use `babel` but with the addition of `@babel/preset-typescript` to keep changes minimal.  

`tsc` will be run separately for type-checking and emitting type declaration files without emitting `js` files.

Here's a checklist of tasks for tracking the progress:

- [ ] Bump `babel` & related dependencies to latest, add `@babel/preset-typescript` (WIP in #40)
- [ ] Add `tsconfig.json` with strict type-checking enabled (WIP in #40)
- [ ] Add `typecheck` script to `package.json#scripts` (WIP in #40)
- [ ] Migrate files in `lib` one-by-one to typescript & make necessary changes for type-checking to pass (WIP in #40)
- [ ] Migrate files in `integrationTests` one-by-one to typescript & make necessary changes for type-checking to pass
- [ ] Add typescript related eslint rules

---

Issues to be discussed / resolved:

- What do the files in the `generator` folder do?

- The necessary changes for typescript migrate would likely result in some breaking changes for downstream users that relied on quirks of the current version of the project. Should we integrate tests for downstream projects (e.g. `jest-runner-prettier`, `jest-runner-eslint` just to name a few) or just go for a major version bump when releasing to indicate that there might breaking changes?

- Can we prefer passing `errorMessage` in `fail.ts` using `options.test.errorMessage`? There are currently two methods to pass the error message using the function `fail`. Here's A non-exclusive list of downstream packages I checked and users seemed to prefer using `options.test.errorMessage` over `options.errorMessage`.
  1) using `options.errorMessage`  
     [`jest-runner-prettier`](https://github.com/keplersj/jest-runner-prettier/blob/22b201e8ca336f59b85cdfd31aa52b4ff24ba771/src/run.js#L32)
  2) using `options.test.errorMessage`  
     [`jest-runner-eslint`](https://github.com/jest-community/jest-runner-eslint/blob/2e20d5192822c9a900a74f0883887f81cf2b6fd9/src/runner/runESLint.js#L76)  
     [`jest-runner-stylelint`](https://github.com/keplersj/jest-runner-stylelint/blob/c2521aa69898a234169c67cb96f22dfee8065175/src/run.js#L25)  
     [`jest-runner-tsd`](https://github.com/jest-community/jest-runner-tsd/blob/351a9ba746b75380a24e796c1aea24395399a49f/src/run.js#L60)
  AFAIK [`jest-runner-mocha`](https://github.com/rogeliog/jest-runner-mocha), [`jest-runner-electron`](https://github.com/d4rkr00t/jest-electron-runner), [`jest-runner-groups`](https://github.com/eugene-manuilov/jest-runner-groups) are not downstream consumers of this project, and these are [all the jest runner projects I am aware of](https://github.com/jest-community/awesome-jest#runners).
  Please let me know if this should be opened as a separate issue.

**Comment by SimenB** [comment]
done in #40
